#<font color='Green'> Course:  ITI1120 - F Winter 2021</font>
#<font color='Green'>Assignment Number: 02</font>
 
# Due Date: <font color='red'>Sunday March 7th, 2021 11:30 PM</font>

<font color='red'> ----- To be filled by the student ----</font>

# Family name, Given name : Le, Cattuong
# Student number : 300001854


### Instructions: (Refer to assignment PDF copy for full instructions)
1- Write your Name and student number in the first cell above (double click to edit).

2- Make sure you provide complete and meaningful docstrings for each function you develop, docstring must include:

    2.1 Type contract, 
    2.2 Function description, including parameter names,
    2.3 Preconditions if any.

## Question #1: <font color='red'>(10 marks)</font>

Write a function called factorsOfN that takes an integer n as a parameter and prints out all the factors of n <font color='red'>(excluding 1 and n)</font>. it should also print the sum of those numbers <font color='red'>(excluding 1 and n)</font>. the fuction should return True if the sum  of the factors printed is smaller than n and returning False otherwise.  Recall that a factor is a number between 1 and n that goes evenly into n. For example:
* if you enter integer: 12, you should get:


```
Enter integer: 12
Factors of 12 = 2 3 4 6 
Sum of the Factors =  15
False
```


* Or, if you enter integer: 9, you should get:



```
Enter integer: 9
Factors of 9 = 3 
Sum of the Factors =  3
True
```



In [31]:
#Question no. 1: 

def factorsOfN(n):
  """Function takes in a single parameter that is an integer
  function will print all the factors of n (excluding 1 and n)
  function will also print out the sum of the factors (excluding 1 and n)
  function will also check if the sum of factors is less than n and will return True; else False
  precondition= n>1
  @type n: int
  @rtype: bool
  """
  factors= ""
  sum=0
  for i in range (2, n):
    if (n%i) == 0:
      sum += i
      i= str(i)
      factors += i + " " 
  n_str=str(n)
  factors_str=str(factors)
  sum_str=str(sum)
  print ("Factors of "+ n_str +" = " + factors_str )
  print ("Sum of the Factors = " + sum_str)
  if sum < n:
    return (True)
  else:
    return (False)

In [32]:
#test1 Question 1:  ~ ask the user to input n then call  factorsOfN from here###
try:
  n= int(input("Enter integer: "))
except ValueError:
  print ("not an integer")
factorsOfN(n)

Enter integer: 12
Factors of 12 = 2 3 4 6 
Sum of the Factors = 15


False

In [33]:
#test2 Question 1:  ~ ask the user to input n then call  factorsOfN from here###
try:
  n= int(input("Enter integer: "))
except ValueError:
  print ("not an integer")
factorsOfN(n)

Enter integer: 9
Factors of 9 = 3 
Sum of the Factors = 3


True

In [34]:
#test3 Question 1:  ~ ask the user to input n then call  factorsOfN from here###
try:
  n= int(input("Enter integer: "))
except ValueError:
  print ("not an integer")
factorsOfN(n)

Enter integer: five
not an integer
Factors of 9 = 3 
Sum of the Factors = 3


True

## Question #2: <font color='red'>(10 marks)</font>

Write a function called H_diamond that takes an integer size as a parameter and prints a size * 2 – 1 wide by size*2 tall diamond of letter H.
for example if you enter integer: 6, you should get:


```
     H     
    HHH    
   HHHHH   
  HHHHHHH  
 HHHHHHHHH 
HHHHHHHHHHH
HHHHHHHHHHH
 HHHHHHHHH
  HHHHHHH
   HHHHH
    HHH
     H
```



In [35]:
#Question no. 2: 

def H_diamond(n):
  """Takes a single parameter that is an integer 
  prints a size * 2 – 1 wide by size*2 tall diamond of the letter H (as in Hamzah).
  @type n: integer
  @rtype: none"""
  if n>0:
    for i in range (n):
      n_str=str(n)
      n_str='H'
      print(" " * (n-1-i), end='')
      print(n_str *(i* 2+1))
    for i in range(n-1, -1, -1):
      print(" " * (n-1-i), end='')
      print(n_str *(i* 2+1))
  else:
    print("Not a positive integer")

In [36]:
#test1 Question 2:  ~ ask the user to input n then call  H_diamond from here###
try:
  n= int(input("Enter integer: "))
except ValueError:
  print ("not an integer")
print("\n")
H_diamond(n)


Enter integer: 6


     H
    HHH
   HHHHH
  HHHHHHH
 HHHHHHHHH
HHHHHHHHHHH
HHHHHHHHHHH
 HHHHHHHHH
  HHHHHHH
   HHHHH
    HHH
     H


In [37]:
#test2 Question 2:  ~ ask the user to input n then call  H_diamond from here###
try:
  n= int(input("Enter integer: "))
except ValueError:
  print ("not an integer")
print("\n")
H_diamond(n)

Enter integer: five
not an integer


     H
    HHH
   HHHHH
  HHHHHHH
 HHHHHHHHH
HHHHHHHHHHH
HHHHHHHHHHH
 HHHHHHHHH
  HHHHHHH
   HHHHH
    HHH
     H


## Question #3: <font color='red'>(10 marks)</font>

Hamzah wants to stop water wastage by creating a new billing system that will make people pay more the more water they use. 
Write a function called WaterBill2021() that takes as input the daily usage in liters of water and number of people living in the house then approximates the amount payable following those rules.

•	Depending on the number of the household members the first 3 litters for each member is free (3 * number of members). Since the daily water intake for humans is ~3L.

•	For the rest each extra 10 litters will cost: 12$ + 3% of the total cost of all the litters which had been used before. (The first 10 litters used after the free ones will cost only 12$, because the total cost before was 0).

•	The last few litters (less than 10) each will cost 2$


For example if you entre 100 litters and 5 members, you should get:

```
Enter litters used daily: 100
Enter number of household memebers: 5
amount of free water =  15
116.70803255504644
```


For example if you entre 15 litters and 6 members, you should get:
```
Enter litters used daily: 15
Enter number of household memebers: 6
amount of free water =  18
0
```







In [38]:
#Question no. 3: 

import math
def WaterBill2021(L,n):
  """function takes in 2 parameters that are both integers
  first 3 liters for each member is free
  rest of extra 10 litters will cost: 12$ + 3% of the total cost of all the liters used before
  last few liters of water that is less than 10L is $2
  @type L: int
  @type n: int
  @rtype: none""" 
  free= 3 * n
  if free>= L:
    free_str=str(free)
    print("amount of free water = " + free_str)
    print ('0')
  
  else:
    free_str=str(free)
    L_charge= L - free
    total= 0
    ten_time= L_charge// 10
    last_few= L_charge % 10
    ten_time_int=int(ten_time)
    for i in range(ten_time):
      water= 12 + 0.03*(total)
      total+= water
    cost2=  last_few * 2

    bill= total + cost2
    bill_str=str(bill)
    print("amount of free water = " + free_str)
    print(bill_str)

In [39]:
#test1 Question 3:  ~ ask the user to input the daily usage and the number of household memebers then call  WaterBill2021 from here###
try:
  L= int(input("Enter litters used daily: "))
  n= int(input("Enter number of household memebers: "))
except ValueError:
  print ("not an integer")
WaterBill2021(L,n)

Enter litters used daily: 100
Enter number of household memebers: 5
amount of free water = 15
116.70803255504644


In [40]:
#test2 Question 3:  ~ ask the user to input the daily usage and the number of household memebers then call  WaterBill2021 from here###
try:
  L= int(input("Enter litters used daily: "))
  n= int(input("Enter number of household memebers: "))
except ValueError:
  print ("not an integer")
WaterBill2021(L,n)

Enter litters used daily: 15
Enter number of household memebers: 6
amount of free water = 18
0


In [41]:
#test3 Question 3:  ~ ask the user to input the daily usage and the number of household memebers then call  WaterBill2021 from here###
try:
  L= int(input("Enter litters used daily: "))
  n= int(input("Enter number of household memebers: "))
except ValueError:
  print ("not an integer")
WaterBill2021(L,n)

Enter litters used daily: five
not an integer
amount of free water = 18
0


## Question #4: <font color='red'>(20 marks)</font>
Write a function named shortest_name that reads number of names (as an input), names typed by the user (as an input(s)) and prints the shortest name (the name that contains the least characters):

* Your method should accept an integer n as a parameter and should then prompt for n names.
* The shortest name should be printed with its first letter in lowercase and all subsequent letters capitalized, regardless of the capitalization the user used when typing in the name. 
* If there is a tie for shortest between two or more names, use the tied name that was typed earliest.
* Also print a message saying that there was a tie, as shown below.
* It is possible that some longer names will tie in length, such as Wassim and hamzah in the example below; but don't print a message unless the tie is between the shortest names.
* You may assume that n is at least 1, that each name is at least 1 character long and at most 30 characters long, and that the user will type single-word names consisting of only letters. 

Example #1: 


```
Enter number of names :5
Enter Name #1: Leah
Enter Name #2: Liv
Enter Name #3: Lexi
Enter Name #4: Lex
Enter Name #5: Lily
lIV's Name is the shortest
(There was a Tie!)
```


Example #2: 


```
Enter number of names :3
Enter Name #1: hamzah
Enter Name #2: wassim
Enter Name #3: sara
sARA's Name is the shortest
```



In [42]:
#Question no.4 :

def shortest_name(n):
  """function takes in a single parameter that is an integer
  shortest name will be printed with its first letter in lowercase and all subsequent letters capitalized
  For tie for shortest between two or more names, tied name that was typed earliest will be printed
  function will print a message saying that there was a tie if there is one
  preconditions:
    -n>0
    -each name is at least 1 character long and at most 30 characters long
    -user will type single-word names consisting of only letters
  @type n:int
  @rtype: none"""
  tie= False
  list_names=[]
  list_shortnames=[]
  for i in range(1,n+1):
    i_str=str(i)
    names=str(input("Enter Name #" + i_str + ":"))
    list_names.append(names.lower())
  for j in range (len(list_names)):
    for k in range (len(list_names[1:])):
      if len(list_names[j]) <= len(list_names[k]):
        list_shortnames.append(list_names[j])
  sorted_shortnames = sorted(list_shortnames, key=len)
  final_list = [] 
  for l in sorted_shortnames: 
    if l not in final_list: 
        final_list.append(l) 
  shortest_name=final_list[0]
  first_letter=shortest_name[0:1].lower()
  rest_letter=shortest_name[1:].upper()
  print(first_letter + rest_letter +"'s Name is the shortest")

  tie = False
  
  
  if len(final_list)>1:
    if len(final_list[0]) == len(final_list[1]):
     tie = True
  if tie:
    print ("(There was a Tie!)")

In [43]:
#test1 Question 4:  ~ ask the user to input the number of names then call  shortest_name from here###
try:
  n= int(input("Enter number of names :"))
except ValueError:
  print ("not an integer")
shortest_name(n)

Enter number of names :5
Enter Name #1:Leah
Enter Name #2:Liv
Enter Name #3:Lexi
Enter Name #4:Lex
Enter Name #5:Lily
lIV's Name is the shortest
(There was a Tie!)


In [44]:
#test2 Question 4:  ~ ask the user to input the number of names then call  shortest_name from here###
try:
  n= int(input("Enter number of names :"))
except ValueError:
  print ("not an integer")
shortest_name(n)

Enter number of names :3
Enter Name #1:hamzah
Enter Name #2:wassim
Enter Name #3:sara
sARA's Name is the shortest


In [45]:
#test3 Question 4:  ~ ask the user to input the number of names then call  shortest_name from here###
try:
  n= int(input("Enter number of names :"))
except ValueError:
  print ("not an integer")
shortest_name(n)

Enter number of names :3
Enter Name #1:Luis
Enter Name #2:Sara
Enter Name #3:Jack
lUIS's Name is the shortest
(There was a Tie!)


# Question #5: <font color='red'>(10 marks)</font>

Write function vowel_bingo(S) that takes a string as input and counts the number of occurrences of vowels in each string.

*	If the string has more than 5 vowels, then the function should print “whammy you lost”. Then exit.

*	If all the 5 vowels appeared in the string, then instead of a whammy the function should print “bingo you have won”. Then exist.

*	If the number of vowels is less than 5 the function should print “playing it safe, eh?”. Then exist.

examples: 


```
Enter String: Le Tour de France
whammy you lost
```


```
Enter String: EDUCATION
bingo you have won
```



```
Enter String: hamzah
playing it safe, eh?
```








In [46]:
#Question no.5 :

def vowel_bingo(s):
  """function takes in a single parameter that is a string
  function will count how many vowels there are in the string
  if string has more than 5 vowels function prints "whammy you lost"
  if string has all 5 vowels then function prints "bingo you have won"
  if string has less than 5 vowels then function prints "playing it safe, eh?"
  @type s: str
  @rtype: none"""
  vowel_a=0
  vowel_e=0
  vowel_i=0
  vowel_o=0
  vowel_u=0
  for i in range(len(s)):
    if s[i]== 'a':
      vowel_a+=1
    elif s[i]== 'e':
      vowel_e+=1
    elif s[i]== 'i':
      vowel_i+=1
    elif s[i]== 'o':
      vowel_o+=1
    elif s[i]== 'u':
      vowel_u+=1
  sum= vowel_a+vowel_e+vowel_i+vowel_o+vowel_u
  if vowel_a>=1 and vowel_e>=1 and vowel_i>=1 and vowel_o>=1 and vowel_u>=1:
    print("bingo you have won")
  elif sum == 5:
    print("whammy you lost")
  elif sum < 5:
    print("playing it safe, eh?")
  elif sum > 5:
    print("whammy you lost")

In [47]:
#test1 Question 5:  ~ ask the user to input a string then call vowel_bingo uare from here###

s=str (input("Enter String:")).lower()
s.lower()
vowel_bingo(s)

Enter String:Le Tour de France
whammy you lost


In [48]:
#test2 Question 5:  ~ ask the user to input a string then call vowel_bingo uare from here###

s=str (input("Enter String:")).lower()
s.lower()
vowel_bingo(s)

Enter String:EDUCATION
bingo you have won


In [49]:
#test3 Question 5:  ~ ask the user to input a string then call vowel_bingo uare from here###

s=str (input("Enter String:")).lower()
s.lower()
vowel_bingo(s)

Enter String:hamzah
playing it safe, eh?


In [50]:
#test4 Question 5:  ~ ask the user to input a string then call vowel_bingo uare from here###

s=str (input("Enter String:")).lower()
s.lower()
vowel_bingo(s)

Enter String:aaeee
whammy you lost


In [51]:
#test5 Question 5:  ~ ask the user to input a string then call vowel_bingo uare from here###

s=str (input("Enter String:")).lower()
s.lower()
vowel_bingo(s)

Enter String:aeiouaeiou
bingo you have won


# Question # 6: <font color='red'>(20 marks)</font>

Hamzah believes that a good password is a password that you can remember while also meet all the requirements of website. So, he created a way to generate a unique password for each website you visit. The way to generate a password is giving below: 
•	Write your mother’s year of birth while pressing shift to generate special characters. For example, 1956 would be typed as !(%^ when you hold shift. 

•	Write your name: “Hamzah”.

•	Write the street number of your grandfather/grandmother house: “674”.

•	Write your favorite movie: “Star Wars”.

•	Write your bf/gf/bff name: “Sara”.

•	Write something related to the website: e.g., for google: “android”.

•	Remove all vowels/spaces from all the strings above. Uppercase your name while force the rest to be lowercase. 

Now with the new Strings you can create your new password for google: 
Start with the first 2 letters of your name “HM”. The last two letters from your favorite movie “rs”. The last two letters from your bf/gf/bff name “sr”. The last two letters from your related word “rd”.

“HM”+”rs”+”sr”+”rd”

Between each of the 4 strings add character from both the street number and birthday.

“HM”+”!6”+”rs”+”(7”+”sr”+”%4”+”rd”+”^”

The new password should be a string of all of those parts : 
“HM!6rs(7sr%4rd^”

Write a function called test_hamzah_password() that takes any user input password and verify if the password was created through hamzah’s logic or not. The function should ask the user to enter all the original strings and then verify that the entered password is a sum of all the parts of the entered strings.

your function should print statements tells if the password is done using hamzah’s way or not.


Example 1:



```
Enter your password: HA!6rs(7sa%4id^
Enter your mother’s year of birth while pressing shift: !(%^
Enter your name: Hamzah
Enter the street number of your grandfather/grandmother house: 674
Enter your favorite movie: Star Wars
Enter your bf/gf/bff name: Sara
Enter something related to the website: android
Great, your password is done using hamzah’s way 
```



Example 2:

 

```
Enter your password: WA!5ay&5Wd#
Enter your mother’s year of birth while pressing shift: !(^!
Enter your name: Wassim
Enter the street number of your grandfather/grandmother house: 753
Enter your favorite movie: the godfather
Enter your bf/gf/bff name: ayah
Enter something related to the website: Iphone
Try again, your password was not done using hamzah’s way 
```




In [52]:
#Question no.6 :

def test_hamzah_password(pw):
  """function takes in a single paramter that is a string
  within the function, it will obtain:
    -mother’s year of birth
    -name
    -street number
    -favorite movie
    -bf/gf/bff name
    -website
  then the function will produce the hamzah way password:
  -2 first letters of name (capital)
  -last 2 letters from favorite movie
  -first 2 letters from bf/gf/bff name
  -last 2 letters of website
  -between each 4 string, 1 character from street number and birthfay will be added
  preconditions: birth year always 4 digits and street address always 3 digits
  @type pw:str
  @rtype: none"""
  bday=str(input("Enter your mother’s year of birth while pressing shift: ")).replace(' ','')
  oldp_name=str(input("Enter your name: ")).upper().strip().replace(' ','')
  address=str(input("Enter the street number of your grandfather/grandmother house: ")).replace(' ','')
  old_movie=str(input("Enter your favorite movie: ")).lower().strip().replace(' ','')
  oldf_name=str(input("Enter your bf/gf/bff name: ")).lower().strip().replace(' ','')
  old_web=str(input("Enter something related to the website: ")).lower().strip().replace(' ','')
  
  p_name= oldp_name.replace(oldp_name[2:],'') #HA
  movie= old_movie.replace(old_movie[:-2],'') #rs
  f_name= oldf_name.replace(oldf_name[2:],'') #sa
  web= old_web.replace(old_web[:-2],'') #id
  bday_address1= bday[0]+address[0] #!6
  bday_address2= bday[1]+address[1] #(7
  bday_address3= bday[2]+address[2] #%4
  bday_address4= bday[3] #^
  if len(pw)>15:
    print("Try again, your password was not done using hamzah’s way")
  if pw[0:2]== p_name and pw[2:4]== bday_address1 and pw[4:6] == movie and pw[6:8]==bday_address2 and pw[8:10]== f_name and pw[10:12]== bday_address3 and pw[12:14]== web and pw[14] == bday_address4:
    print("Great, your password is done using hamzah’s way")
  else:
    print("Try again, your password was not done using hamzah’s way")


In [53]:
#test1 Question 6:  ~ ask the user to input a password then call test_hamzah_password uare from here###
pw=str(input("Enter your password: "))
test_hamzah_password(pw)

Enter your password: HA!6rs(7sa%4id^
Enter your mother’s year of birth while pressing shift: !(%^
Enter your name: Hamzah
Enter the street number of your grandfather/grandmother house: 674
Enter your favorite movie: Star Wars
Enter your bf/gf/bff name: Sara
Enter something related to the website: android
Great, your password is done using hamzah’s way


In [54]:
#test2 Question 6:  ~ ask the user to input a password then call test_hamzah_password uare from here###
pw=str(input("Enter your password: "))
test_hamzah_password(pw)

Enter your password: WA!5ay&5Wd#
Enter your mother’s year of birth while pressing shift: !(^!
Enter your name: Wassim
Enter the street number of your grandfather/grandmother house: 753
Enter your favorite movie: the godfather
Enter your bf/gf/bff name: ayah
Enter something related to the website: Iphone
Try again, your password was not done using hamzah’s way


# Question # 7: <font color='red'>(10 marks)</font>

Lossy compression/encoding/encryption is a class of methods where the loss of some of the data is desired (usually to reduce the size of the data). A good example of this is images/Videos as most of the videos you get from the internet have gone through this and lost a large amount of the original data ( though you will not be able to see the difference since those methods tries remove unnoticeable things. You can google this subject to learn more.  
Write a simple function called lossy_encryption( ) that takes input string and it should returns new string (encrypted version of input string).
Your function should take a triplet and delete the middle character while reversing the order of the other two. In case your string length is not a multiple of three, add the one/two characters to the end of the encrypted string.

To validate your solution, if you use input " 123456 ", your function must return "3164"



In [55]:
#Question no.7 :

def lossy_encryption(s):
  """function takes in a single parameter that is a string
  function will take a triplet, delete the middle character while reversing the order of the other two
  if string not a multiple of three, add thpse characters at the end
  @type s: str
  @rtype: none"""

  n = 3
  triplet_list=[]

  for i in range(0, len(s), n):
    triplet_list.append(s[i : i + n])
  
  deleted=''
  for j in triplet_list:
    if len(j)==3:
      j = [j[0::2]]
      j_str=str(j)
      length2=len(j_str)
      reverse=j_str[length2::-1]
      deleted+=reverse
    elif len(j)!=3:
        j_str=str(j)
        deleted+=j_str
  deleted=deleted. replace("[",'').replace("]",'').replace("'",'')
  print(deleted)  

In [56]:
#test1 Question 7:  ~ ask the user to input a String then call lossy_encryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_encryption(s)

Enter String to be Encrypted 123456
3164


In [57]:
#test2 Question 7:  ~ ask the user to input a String then call lossy_encryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_encryption(s)

Enter String to be Encrypted 12345678
316478


In [58]:
#test3 Question 7:  ~ ask the user to input a String then call lossy_encryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_encryption(s)

Enter String to be Encrypted abcdef
cafd


# Question # 8: <font color='red'>(10 marks)</font>

Write a simple function called lossy_decryption( ) that takes input string (the encrypted one in question #8 above) and it should return a copy similar to the original but with “*” in place of the lost characters . 
To validate your solution, if you use input "3164", your function must return "1*34*6 ". notice that we can guess that the original string was “123456”, most of lossy decryption methods do some guess work.



In [59]:
#Question no.8 :

def lossy_decryption(s):
  """function takes in a single parameter that is a strin
  function will add a * in place of the lost characters
  @type s: string
  @rtype:none"""
  n = 2
  double_list=[]

  for i in range(0, len(s), n):
    double_list.append(s[i : i + n])

  add=''
  for j in double_list:
      j_str=str(j)
      j_new = j_str[:1] + "*" + j_str[1:]
      j_str=str(j_new)
      length2=len(j_str)
      reverse=j_str[length2::-1]
      add+=reverse
  print(add)

In [60]:
#test1 Question 8:  ~ ask the user to input a String then call lossy_decryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_decryption(s)

Enter String to be Encrypted 3164
1*34*6


In [61]:
#test2 Question 8:  ~ ask the user to input a String then call lossy_decryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_decryption(s)

Enter String to be Encrypted 316497
1*34*67*9


In [62]:
#test3 Question 8:  ~ ask the user to input a String then call lossy_decryption from here###
s=str(input("Enter String to be Encrypted "))
lossy_decryption(s)

Enter String to be Encrypted cafd
a*cd*f
